### ISSUE TITLE
Dialog does not scroll when content spans past max height

### ISSUE THREAD

**Issue by arrenleung** [AlaskaAirlines/auro-dialog#15]
### Please verify the version of auro-dialog you have installed

1.0.8

### Please describe the bug

1. Create an auro-dialog component with content that spans past the max height of the dialog
2. Open the dialog
3. See that the the content overflows out of the dialog's container and no scroll bar interaction appears

Also visible on the docsite's dialogs on a mobile breakpoint

<img width="909" alt="image" src="https://github.com/AlaskaAirlines/auro-dialog/assets/43892293/ee70b076-e32b-4324-9cef-256755c17ec0">

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

When dialog content spans longer than the dialog's max-height, the content does not overflow and is instead accessible through a scrolling interaction.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Additional context

The bug is not reproducible in the deprecated auro-interruption dialog component

### Exit criteria

When dialog content spans longer than the dialog's max-height, the content does not overflow and is instead accessible through a scrolling interaction.

**Comment by Patrick-Daly-AA** [comment]
As part of fixing this bug, we'll be adding a Doc Site Example that will ensure proper scrolling.
