### ISSUE TITLE
auro-dialog: sm, md, lg properties

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dialog#2]
## Is your feature request related to a problem? Please describe.
The feature requested is to add new properties to the dialog experience. Small, Medium, and Large options to better suit the content that will be slotted in. 

https://app.abstract.com/projects/c3b52e9f-30c7-4774-b721-2434130de005/branches/d5090941-2e15-42db-8b0c-f2c7a3e38a2d/commits/9238a5adb26fd4700b2fc6f5e7a711048948f10b

## Describe the solution you'd like
In the auro-dialog the request is to have three boolean attributes, `sm`, `md`, `lg`. When using these attributes the dialog will respond with the associated size requirement. 

### Reference 
https://github.com/AlaskaAirlines/auro/issues/11

**Comment by blackfalcon** [comment]
@Crea-Ive @gusnaughton updates are posted to http://sprint-20.surge.sh/components/auro/dialog, will schedule time for review.

**Comment by blackfalcon** [comment]
Updates have been pushed to http://sprint-20.surge.sh/components/auro/dialog for review. 

@Crea-Ive the size feature has been updated as we discussed, and adjustments were made to support better useability whereas the dialog always appears the same distance from the top and the height has a max-height of 90% for all dialogs. This will allow for more flexibility of content to be added length-wise before scrolling appears.

@tsalright @geoffrich @gusnaughton the PR is pushed for review. Could use help with tests. Need an assist for how to test for a function that requires a click. The issue I have is that the trigger is not part of the component, so unsure how to test this.

**Comment by geoffrich** [comment]
@blackfalcon I would include the trigger as part of the fixture.

```js
const el = await fixture(html`
  <button>Trigger</button>
  <auro-dialog open="true">
	<span slot="header">It's a dialog</span>
	<span slot="content">Hello World!</span>
  </auro-dialog>
`);

const button = document.querySelector('button');
const dialog = document.querySelector('auro-dialog');

button.addEventListener('click', () => { dialog.setAttribute("open", true) };
```

Then trigger a click on the button. If this will be used in multiple tests I'd add a helper function to set this up.
