### ISSUE TITLE
Close "X" icon is not appearing in the UI

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-dialog#30]
### Please verify the version of auro-dialog you have installed

@latest

### Please describe the bug

1. Go to "https://auro.alaskaair.com/components/auro/dialog"
2. Click OPEN DEFAULT DIALOG
3. Notice that the "X" icon is not appearing in the UI

<img width="1085" alt="Screenshot 2024-11-04 at 5 34 35 PM" src="https://github.com/user-attachments/assets/2cf351a3-aea5-4096-af87-b143c3c2907d">

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

The requested icon should appear in the designated slot.

### What browsers are you seeing the problem on?

Chrome

### Additional context

n/a

### Exit criteria

This issue could be closed once the icon appears as intended in the UI.

**Comment by jason-capsule42** [comment]
I just ran the localhost of the main branch and the icon is rendering just fine for me. Can you double check this bug @blackfalcon and maybe we can pair program together if you are still seeing it broken?

**Comment by blackfalcon** [comment]
Did the following steps: 

1. git checkout main
2. git pull
3. npm ci
4. npm run build:ci
5. npm run dev

Unable to repro issue. 

Not sure why these same steps didn't work yesterday, but ... code... 

Closing issue.
